// Mycel's art never owns combat. Accepted casts, budgets and clocks belong to the gardener.
var mycelSerial=0,mycelTimers=new WeakMap(),mycelEntityClocks=new WeakMap();
var MYCEL_TIMERS={primaryCool:.58,cloudCool:5,utilityCool:6,specialCool:12,chorusT:4,primaryPoseT:.2,cloudPoseT:.2,bloomPoseT:.2};
function mycelMember(m){return m===undefined?(coop?(coopActor||coop.members[coop.me]):null):m;}
function mycelActor(m){return m?coopMemberAvatar(m):P;}
function mycelOwner(m){return m?m.id:'';}
function mycelOwners(){return coop?Object.values(coop.members):[null];}
function mycelClass(m){return m?m.classId:rogueRun.classId;}
function mycelId(n){return Number.isSafeInteger(n)&&n>0&&n<=1e9?n:0;}
function mycelNumber(n,max){return Number.isFinite(n)?Math.max(0,Math.min(max,n)):0;}
function mycelWorld(n){return Number.isInteger(n)&&n>=1&&n<=20?n:0;}
function mycelCoordinate(n){return Number.isFinite(n)&&Math.abs(n)<1e7?n:0;}
function mycelNextSerial(){mycelSerial=Math.min(1e9,mycelSerial+1);return mycelSerial;}
function mycelPeek(m){m=mycelMember(m);return (m||rogueRun).mycel||null;}
function mycelBuild(m){m=mycelMember(m);var b=m?m.perks:rogueRun.perks,t=m?m.traits:ownTraits();return mycelCleanBuild(Object.assign({},b,{emberStacks:t&&t.embers||0}));}
function mycelCleanBuild(raw){var b={};['colony','ferment','symbiosis','cadence'].forEach(function(k){b[k]=Math.floor(mycelNumber(raw&&raw[k],3));});['outbreak','symphony'].forEach(function(k){b[k]=Math.floor(mycelNumber(raw&&raw[k],1));});b.mulch=Math.floor(mycelNumber(raw&&raw.mulch,4));b.emberStacks=Math.floor(mycelNumber(raw&&raw.emberStacks,99));return b;}
function mycelPrimaryInterval(m){return .58*Math.pow(.88,mycelBuild(m).cadence);}
function mycelRemaining(q,k){var n=mycelNumber(q&&q[k],MYCEL_TIMERS[k]),t=mycelTimers.get(q);if(t&&Number.isFinite(t[k]))n=Math.min(n,Math.max(0,(t[k]-performance.now())/1000));return n<1e-8?0:n;}
function mycelSetTimer(q,k,n){var t=mycelTimers.get(q);if(!t){t={};mycelTimers.set(q,t);}q[k]=mycelNumber(n,MYCEL_TIMERS[k]);t[k]=performance.now()+q[k]*1000;}
function mycelAge(o,max){var c=mycelEntityClocks.get(o),raw=mycelNumber(o&&o.totalAge!=null?o.totalAge:o&&o.age,max);return c?Math.min(max,Math.max(raw,(performance.now()-c.born)/1000)):raw;}
function mycelBindClock(o,age){mycelEntityClocks.set(o,{born:performance.now()-age*1000});return o;}
function mycelDebts(raw,maxH,maxW,windows){var list=[];(Array.isArray(raw)?raw:[]).slice(0,120).forEach(function(d){var id=mycelId(d&&d.id);if(!id)return;var found=list.find(function(p){return p.id===id;}),n={id:id,healthUsed:mycelNumber(d.healthUsed,maxH),waterUsed:mycelNumber(d.waterUsed,maxW)};if(windows)n.left=mycelNumber(d.left,1);if(found){found.healthUsed=Math.max(found.healthUsed,n.healthUsed);found.waterUsed=Math.max(found.waterUsed,n.waterUsed);if(windows)found.left=Math.max(found.left,n.left);}else if(list.length<30)list.push(n);});return list;}
function mycelCaptureCloud(raw){if(!raw||!mycelId(raw.serial)||!mycelId(raw.startTag))return null;var life=Math.max(3,mycelNumber(raw.life,6)),age=mycelAge(raw,6);return {serial:raw.serial,startTag:raw.startTag,world:mycelWorld(raw.world),x:mycelCoordinate(raw.x),y:mycelCoordinate(raw.y),life:life,age:age,pulseMask:Math.floor(mycelNumber(raw.pulseMask,7)),build:mycelCleanBuild(raw.build)};}
function mycelCaptureBloom(raw){if(!raw||!mycelId(raw.serial)||!mycelId(raw.startTag))return null;var allies=[];(Array.isArray(raw.allies)?raw.allies:[]).slice(0,16).forEach(function(a){if(!a||typeof a.id!=='string'||a.id.length>64)return;var found=allies.find(function(x){return x.id===a.id;}),used=mycelNumber(a.usedHP,12);if(found)found.usedHP=Math.max(found.usedHP,used);else if(allies.length<4)allies.push({id:a.id,usedHP:used});});return {serial:raw.serial,startTag:raw.startTag,world:mycelWorld(raw.world),x:mycelCoordinate(raw.x),y:mycelCoordinate(raw.y),age:mycelAge(raw,5.6),pulseMask:Math.floor(mycelNumber(raw.pulseMask,7)),cancelled:raw.cancelled?1:0,readied:raw.readied?1:0,build:mycelCleanBuild(raw.build),chorusPulse:raw.chorusPulse?1:0,reviveId:mycelId(raw.reviveId),reviveKind:Math.floor(mycelNumber(raw.reviveKind,100)),reviveSeed:Number.isInteger(raw.reviveSeed)?raw.reviveSeed>>>0:0,reviveConsumed:raw.reviveConsumed?1:0,plots:mycelDebts(raw.plots,.12,.15,false),allies:allies,hpUsed:Math.min(12,Math.max(mycelNumber(raw.hpUsed,12),allies.reduce(function(n,a){return n+a.usedHP;},0)))};}
function mycelCaptureDrift(raw){if(!raw||!mycelId(raw.serial)||!mycelId(raw.startTag))return null;var total=mycelAge(raw,1.15),q={serial:raw.serial,startTag:raw.startTag,world:mycelWorld(raw.world),face:raw.face<0?-1:1,totalAge:total,age:Math.min(.35,total),phase:raw.phase===1&&total<.35-1e-8?1:raw.phase&&total<1.15-1e-8&&!raw.landingConsumed?2:0,travel:mycelNumber(raw.travel,48),launchVY:Math.max(-90,Math.min(0,Number.isFinite(raw.launchVY)?raw.launchVY:0)),riseLimit:mycelNumber(raw.riseLimit,90*90/(2*430)),riseUsed:mycelNumber(raw.riseUsed,90*90/(2*430)),seenAir:raw.seenAir?1:0,landingLease:Math.min(.8,Math.max(0,1.15-total)),landingConsumed:raw.landingConsumed?1:0,landingPlantId:mycelId(raw.landingPlantId)};['originX','originY','x','y','apexY'].forEach(function(k){q[k]=mycelCoordinate(raw[k]);});q.vx=Math.max(-180,Math.min(180,+raw.vx||0));q.vy=Math.max(-500,Math.min(500,+raw.vy||0));q.riseUsed=Math.min(q.riseUsed,q.riseLimit);return q;}
function mycelCaptureState(raw){raw=raw||{};var q={world:mycelWorld(raw.world)||worldLevel(),culture:mycelNumber(raw.culture,6),networkIds:[],clouds:[],drift:mycelCaptureDrift(raw.drift),bloom:mycelCaptureBloom(raw.bloom),symbiosis:mycelDebts(raw.symbiosis,.045,.105,true)};Object.keys(MYCEL_TIMERS).forEach(function(k){q[k]=mycelRemaining(raw,k);});['primary','cloud','bloom'].forEach(function(k){q[k+'Serial']=mycelId(raw[k+'Serial']);q[k+'StartTag']=mycelId(raw[k+'StartTag']);q[k+'Face']=raw[k+'Face']<0?-1:1;});q.chorusSerial=mycelId(raw.chorusSerial);q.chorusPlantId=mycelId(raw.chorusPlantId);(Array.isArray(raw.networkIds)?raw.networkIds:[]).forEach(function(id){if(mycelId(id)&&q.networkIds.length<3&&!q.networkIds.includes(id))q.networkIds.push(id);});(Array.isArray(raw.clouds)?raw.clouds:[]).slice(0,8).forEach(function(c){c=mycelCaptureCloud(c);if(c&&q.clouds.length<2&&!q.clouds.some(function(d){return d.serial===c.serial;}))q.clouds.push(c);});q.symbiosis.forEach(function(d,i){var source=(Array.isArray(raw.symbiosis)?raw.symbiosis:[]).find(function(s){return s.id===d.id;}),clock=mycelEntityClocks.get(source);if(clock)d.left=Math.min(d.left,Math.max(0,(clock.until-performance.now())/1000));});return q;}
function mycelRestoreState(raw,m){var q=mycelCaptureState(raw);if(q.world!==worldLevel()){q.world=worldLevel();q.clouds=[];q.drift=q.bloom=null;q.networkIds=[];q.symbiosis=[];}q.clouds=q.clouds.filter(function(c){return c.world===worldLevel()&&c.age<=c.life;});if(q.bloom&&q.bloom.world!==worldLevel())q.bloom=null;if(q.drift&&q.drift.world!==worldLevel())q.drift=null;mycelRebaseState(q);return q;}
function mycelRebaseState(q,now){now=Number.isFinite(now)?now:performance.now();var t={};Object.keys(MYCEL_TIMERS).forEach(function(k){t[k]=now+q[k]*1000;});mycelTimers.set(q,t);q.clouds.forEach(function(c){mycelEntityClocks.set(c,{born:now-c.age*1000});});if(q.bloom)mycelEntityClocks.set(q.bloom,{born:now-q.bloom.age*1000});if(q.drift)mycelEntityClocks.set(q.drift,{born:now-q.drift.totalAge*1000});q.symbiosis.forEach(function(d){mycelEntityClocks.set(d,{until:now+d.left*1000});});return q;}
function mycelState(m){m=mycelMember(m);var holder=m||rogueRun;if(!holder.mycel)holder.mycel=mycelRestoreState({world:worldLevel()});return holder.mycel;}
function mycelRebaseClocks(m,now){return mycelRebaseState(mycelState(m),now);}
function mycelRefreshClocks(m){var q=mycelState(m);Object.keys(MYCEL_TIMERS).forEach(function(k){q[k]=mycelRemaining(q,k);});q.clouds.forEach(function(c){c.age=mycelAge(c,6);});if(q.bloom)q.bloom.age=mycelAge(q.bloom,5.6);if(q.drift){var d=q.drift;d.totalAge=mycelAge(d,1.15);d.age=Math.min(.35,d.totalAge);d.landingLease=Math.min(.8,Math.max(0,1.15-d.totalAge));if(d.phase===1&&d.totalAge>=.35-1e-8)d.phase=d.landingConsumed?0:2;if(d.totalAge>=1.15-1e-8)d.phase=0;}q.symbiosis.forEach(function(d){var c=mycelEntityClocks.get(d);if(c)d.left=Math.max(0,(c.until-performance.now())/1000);});return q;}
function mycelCaptureShot(s){if(!s||s.kind!=='spore'||!mycelId(s.primarySerial)||!mycelId(s.startTag))return null;var out={id:mycelId(s.id),owner:typeof s.owner==='string'?s.owner:'',world:mycelWorld(s.world),kind:'spore',primarySerial:s.primarySerial,startTag:s.startTag,initialRewardConsumed:s.initialRewardConsumed?1:0,seenIds:[],build:mycelCleanBuild(s.build||s.perks),life:mycelNumber(s.life,1.15),hits:Math.floor(mycelNumber(s.hits,1)),pierce:0,hit:''};['x','y','tx','ty'].forEach(function(k){out[k]=mycelCoordinate(s[k]);});out.vx=Math.max(-140,Math.min(140,+s.vx||0));out.vy=Math.max(-140,Math.min(140,+s.vy||0));out.damage=1+.2*out.build.ferment;(Array.isArray(s.seenIds)?s.seenIds:[]).forEach(function(id){if(mycelId(id)&&out.seenIds.length<4&&!out.seenIds.includes(id))out.seenIds.push(id);});out.hit=out.seenIds.map(function(id){return ','+id+',';}).join('');out.perks=out.build;return out;}
function mycelRestoreShot(s){return mycelCaptureShot(s);}
function mycelCapturePestEvents(k){function list(raw,max){var out=[];(Array.isArray(raw)?raw:[]).slice(0,32).forEach(function(e){if(!e||typeof e.owner!=='string'||e.owner.length>64||!mycelId(e.serial)||!mycelId(e.world)||e.world>20)return;var found=out.find(function(q){return q.owner===e.owner&&q.serial===e.serial&&q.world===e.world;}),n={owner:e.owner,serial:e.serial,world:e.world,mask:Math.floor(mycelNumber(e.mask,7))};if(found)found.mask|=n.mask;else if(out.length<max)out.push(n);});return out;}return {mycelCloudEvents:list(k&&k.mycelCloudEvents,8),mycelBloomEvents:list(k&&k.mycelBloomEvents,4)};}
function mycelRestorePestEvents(raw,states){var q=mycelCapturePestEvents(raw);function bound(e,kind){var m=coop?coop.members[e.owner]:null,s=states&&states[e.owner]||mycelPeek(m);return e.world===worldLevel()&&(coop?!!m&&!m.left&&m.classId==='herbalist':e.owner===''&&rogueRun.classId==='herbalist')&&s&&(kind==='cloud'?s.clouds.some(function(c){return c.serial===e.serial&&c.world===e.world;}):s.bloom&&s.bloom.serial===e.serial&&s.bloom.world===e.world); }q.mycelCloudEvents=q.mycelCloudEvents.filter(function(e){return bound(e,'cloud');});q.mycelBloomEvents=q.mycelBloomEvents.filter(function(e){return bound(e,'bloom');});return q;}
function mycelWetPoint(x,y){return highTideMode()?y>=rogueRun.survival.waterY:playerWetAt(x,y);}
function mycelWetBody(a,m){m=mycelMember(m);return !!(a&&(mycelWetPoint(a.x,a.y)||a.wet||a.st==='float'||highTideMode()&&highTideHead({p:a,member:m})>=rogueRun.survival.waterY));}
function mycelPlantPoint(p,point){var base=p.tideVine&&highTideMode()?rogueRun.survival.base:surfaceY(p.x),height=p.tideVine&&highTideMode()?rogueRun.survival.height:plantClimbHeight(p),y=Math.max(base-height,Math.min(base-2,point.y));return p.tideVine&&highTideMode()?highTideRoutePoint(Math.max(0,base-y)):{x:p.x+plantLean(p,base-y,tSec),y:y};}
function mycelPlotsAt(point,r,living){return gardenPlots.filter(function(p){return mycelId(p.id)&&(!living||!p.dead&&p.health>0);}).map(function(p){var at=mycelPlantPoint(p,point);return {id:p.id,plot:p,x:at.x,y:at.y,distance:Math.hypot(at.x-point.x,at.y-point.y),wet:p.moisture>=.20};}).filter(function(p){return p.distance<=r+1e-8&&combatLineClear(point.x,point.y,p.x,p.y);}).sort(function(a,b){return a.distance-b.distance||a.id-b.id;});}
function mycelNetwork(m,point){m=mycelMember(m);var a=mycelActor(m);return mycelPlotsAt(point||{x:a.x,y:a.y-12},58,true).slice(0,3);}
function mycelLocal(m){return !m||!coop||m.id===coop.me||coopActor&&m.id===coopActor.id;}
function mycelAutomaticIdle(a,m){return cairnAutomaticIdle(a,m);}
function mycelWake(m){if(mycelLocal(m)&&mycelAutomaticIdle(P,m)){P.autoIdlePose=false;P.st='free';P.still=0;P.lampLit=0;setAnim('idle');}}
function mycelPresent(m){var a=mycelActor(m);return mycelClass(m)==='herbalist'&&(!m||!m.left)&&(!Number.isFinite(a.world)||a.world===worldLevel())&&!seedDown(m)&&!mycelWetBody(a,m)&&!a.exitClimb&&!(mycelLocal(m)&&(warp||climb&&climb.exit));}
function mycelCanAct(m,verb){m=mycelMember(m);var a=mycelActor(m),local=mycelLocal(m);if(!mycelPresent(m)||runIsPaused()||a.tun>0||a.pounce||a.dodgeT>0||a.dodging||local&&warp)return false;var free=a.st==='free'||mycelAutomaticIdle(a,m),shoot=verb==='primary'&&['climb','ladder'].includes(a.st)&&!a.exitClimb;if(!free&&!shoot)return false;var policy=mycelPhasePolicy(m);if(verb==='primary')return !policy.blockPrimary;if(policy.blockSecondary)return false;if(verb==='drift'&&(a.gardenTend||a.reviveHeld||a.tideTend||local&&(task||holdWater||heldDown||heldSpace||swipeDown||gardenPress)))return false;if(a.grounded&&!cairnSupportPoint(a.x,a.y,a.platform||null))return false;return true;}
function mycelPhasePolicy(m){m=mycelMember(m);var q=mycelPeek(m)||{},d=q.drift?mycelCaptureDrift(q.drift):null,local=mycelLocal(m),cancelled=local&&coopGuest()?P.mycelCancelledCasts||{}:{},active=d&&d.world===worldLevel()&&d.phase===1&&cancelled.drift!==d.serial,lease=d&&d.world===worldLevel()&&d.phase===2&&!d.landingConsumed&&cancelled.drift!==d.serial,out={phase:active?'drift':lease?'landing':'none',blockPrimary:false,blockSecondary:!!active,blockUtility:!!active,blockSpecial:!!active,blockJump:!!active,blockDodge:false,blockClimb:!!active,blockTend:!!active,blockAutocatch:!!active,lockSteer:!!active};['primary','cloud','bloom'].forEach(function(k){out[k+'Serial']=q[k+'Serial']||0;out[k+'Face']=q[k+'Face']||1;out[k+'PoseT']=cancelled[k]===q[k+'Serial']?0:mycelRemaining(q,k+'PoseT');});out.driftSerial=d&&d.serial||0;return out;}
function mycelCloudPlacement(aim,m){m=mycelMember(m);var a=mycelActor(m),point={x:aim&&aim.x,y:aim&&aim.y},valid=Number.isFinite(point.x)&&Number.isFinite(point.y)&&Math.hypot(point.x-a.x,point.y-(a.y-12))<=80+1e-8&&!mycelWetPoint(point.x,point.y)&&!window.MaxStageLayout.inRock(stageLayout(),point.x,point.y)&&point.y<(highTideMode()?rogueRun.survival.base+110:surfaceY(point.x))&&combatLineClear(a.x,a.y-12,point.x,point.y);return {valid:!!valid,x:point.x,y:point.y,reason:valid?'':'point'};}
function mycelOwned(m,fn){return m&&coop&&m.id!==coop.me&&(!coopActor||coopActor.id!==m.id)?coopWithMember(m,fn):fn();}
function mycelCastBySerial(owner,serial,world){var m=coop?coop.members[owner]:null,q=coop?m&&mycelPeek(m):owner===''?mycelPeek(null):null;if(!q||world!==worldLevel()||(m&&m.left)||mycelClass(m)!=='herbalist')return null;return q.clouds.find(function(c){return c.serial===serial&&c.world===world;})||q.bloom&&q.bloom.serial===serial&&q.bloom.world===world&&q.bloom||null;}
function mycelCastOwner(cast){var found;mycelOwners().some(function(m){if(m&&m.left||mycelClass(m)!=='herbalist')return false;var q=mycelPeek(m);if(q&&(q.bloom===cast||q.clouds.includes(cast))){found={member:m,owner:mycelOwner(m),kind:q.bloom===cast?'bloom':'cloud'};return true;}return false;});return found||null;}
function mycelContactPoint(cast,point,r){return !!(point&&Number.isFinite(point.x)&&Number.isFinite(point.y)&&Math.hypot(point.x-cast.x,point.y-cast.y)<=r+1e-8&&combatLineClear(cast.x,cast.y,point.x,point.y));}
function mycelRestoreCast(cast,p,health,water){var zero={health:0,water:0},owner=mycelCastOwner(cast);if(coopGuest()||!owner||owner.kind!=='bloom'||cast.world!==worldLevel()||mycelAge(cast,5.6)>=5.6||gardenPlots.indexOf(p)<0||p.dead||!(p.health>0||Number.isFinite(p.health)&&p.health<=0&&cast.reviveConsumed&&p.id===cast.reviveId&&p.kind===cast.reviveKind&&(p.seed>>>0)===cast.reviveSeed)||!mycelContactPoint(cast,mycelPlantPoint(p,cast),48))return zero;var d=cast.plots.find(function(d){return d.id===p.id;});if(!d){if(cast.plots.length>=30)return zero;d={id:p.id,healthUsed:0,waterUsed:0};cast.plots.push(d);}var h=Math.max(0,Math.min(+health||0,.12-d.healthUsed,1-p.health)),w=Math.max(0,Math.min(+water||0,.15-d.waterUsed,1-p.moisture));d.healthUsed+=h;d.waterUsed+=w;p.health+=h;p.moisture+=w;if(h||w)p.pulse=Math.max(p.pulse||0,1);return {health:h,water:w};}
function mycelRestoreContext(cast){var owner=mycelCastOwner(cast);if(!owner)return null;var ctx={kind:owner.kind,owner:owner.owner,serial:cast.serial,world:cast.world,x:cast.x,y:cast.y,r:owner.kind==='bloom'?48:44,build:cast.build,skipHitStagger:true,useful:false};ctx.canContact=function(point){return mycelContactPoint(cast,point,ctx.r);};ctx.restore=function(p,h,w){var delivered=owner.kind==='bloom'?mycelRestoreCast(cast,p,h,w):{health:0,water:0};if(delivered.health||delivered.water)ctx.useful=true;return delivered;};ctx.markUseful=function(){ctx.useful=true;};return ctx;}
function mycelSetBurnCause(k,ctx){if(!k)return;if(ctx&&(ctx.kind==='cloud'||ctx.kind==='bloom')){k.mycelBurnOwner=ctx.owner;k.mycelBurnSerial=ctx.serial;k.mycelBurnWorld=ctx.world;k.mycelBurnKind=ctx.kind;}else{k.mycelBurnOwner='';k.mycelBurnSerial=k.mycelBurnWorld=0;k.mycelBurnKind='';}}
function mycelBurnContext(k){
  if(!k||!k.mycelBurnSerial&&!k.mycelBurnKind&&!k.mycelBurnWorld&&!k.mycelBurnOwner)return null;
  var valid=mycelId(k.mycelBurnSerial)&&mycelWorld(k.mycelBurnWorld)===worldLevel()&&typeof k.mycelBurnOwner==='string'&&['cloud','bloom'].includes(k.mycelBurnKind),cast=valid&&mycelCastBySerial(k.mycelBurnOwner,k.mycelBurnSerial,k.mycelBurnWorld),ctx=cast&&mycelRestoreContext(cast);if(ctx&&ctx.kind===k.mycelBurnKind)return ctx;
  return {kind:k.mycelBurnKind==='bloom'?'bloom':'cloud',owner:typeof k.mycelBurnOwner==='string'?k.mycelBurnOwner:'',serial:mycelId(k.mycelBurnSerial),world:mycelWorld(k.mycelBurnWorld),build:mycelCleanBuild({}),skipHitStagger:true,useful:false,canContact:function(){return false;},restore:function(){return {health:0,water:0};},markUseful:function(){}};
}

function mycelCue(q,verb,serial,tag,face){q[verb+'Serial']=serial;q[verb+'StartTag']=tag;q[verb+'Face']=face<0?-1:1;mycelSetTimer(q,verb+'PoseT',.2);}
function mycelPrimaryWorld(aim,tag){
  var m=mycelMember();if(coopGuest()||!mycelCanAct(m,'primary'))return false;var q=mycelRefreshClocks(m);if(q.primaryCool>0)return false;aim=combatAim(aim);var a=mycelActor(m),angle=Math.atan2(aim.y-(a.y-13),aim.x-a.x),b=mycelBuild(m),serial=mycelNextSerial();mycelWake(m);if(Math.abs(aim.x-a.x)>1)a.face=aim.x>a.x?1:-1;
  classShots.push({id:++classShotId,owner:mycelOwner(m),world:worldLevel(),kind:'spore',primarySerial:serial,startTag:mycelId(tag)||serial,initialRewardConsumed:0,seenIds:[],build:b,perks:b,x:a.x+Math.cos(angle)*6,y:a.y-13+Math.sin(angle)*6,vx:Math.cos(angle)*140,vy:Math.sin(angle)*140,tx:aim.x,ty:aim.y,life:1.15,damage:1+.2*b.ferment,pierce:0,hit:'',hits:0});mycelSetTimer(q,'primaryCool',mycelPrimaryInterval(m));bombCool=bombCoolMax=q.primaryCool;mycelCue(q,'primary',serial,mycelId(tag)||serial,a.face);combatFx('mycel-dart',a.x,a.y-13,7,a.face);return true;
}
function mycelThreat(k,p){
  var root=runHazards.find(function(h){return h.id===k.rootHazard&&h.tell>0&&h.power>0;}),tide=highTideMode()&&p.tideVine&&k.tide&&k.windup>0&&(k.tideType==='sap'||k.tideBoss&&k.bossId==='moon-moth'&&k.healing),drain=k.draining&&k.kind===10?gardenPlots.filter(function(p){return !p.dead&&p.health>0;}).sort(function(a,b){return a.moisture-b.moisture;})[0]:null;
  var threatened=tide||root&&Math.abs(root.x-p.x)<root.r+4&&Math.abs(root.y-surfaceY(p.x))<20||isRat(k)&&k.ratTargetId===p.id&&(k.windup>0||k.attackT>0)||k.windup>0&&(k.target===p||k.attackTarget===p)||p===drain;
  return threatened?{plant:p,root:root&&root.id||0,windup:k.windup||0,attack:k.attackT||0,charge:k.chargeT||0,draining:!!k.draining,flee:k.flee||0}:null;
}
function mycelSymbiosis(q,shot){var rank=shot.build.symbiosis;if(!rank)return;q.symbiosis=q.symbiosis.filter(function(d){var clock=mycelEntityClocks.get(d);if(clock)d.left=Math.max(0,(clock.until-performance.now())/1000);return d.left>1e-8||gardenPlots.some(function(p){return p.id===d.id;});});mycelPlotsAt({x:shot.x,y:shot.y},34,true).forEach(function(p){var d=q.symbiosis.find(function(d){return d.id===p.id;});if(d){if(d.left<=1e-8){d.healthUsed=d.waterUsed=0;d.left=0;}}else{if(q.symbiosis.length>=30){var expired=q.symbiosis.findIndex(function(d){return d.left<=1e-8;});if(expired<0)return;q.symbiosis.splice(expired,1);}d={id:p.id,healthUsed:0,waterUsed:0,left:0};q.symbiosis.push(d);}var h=Math.max(0,Math.min(.015*rank-d.healthUsed,1-p.plot.health)),w=Math.max(0,Math.min(.035*rank-d.waterUsed,1-p.plot.moisture));if(!(h||w))return;if(d.left<=0){d.left=1;mycelEntityClocks.set(d,{until:performance.now()+1000});}d.healthUsed+=h;d.waterUsed+=w;p.plot.health+=h;p.plot.moisture+=w;p.plot.pulse=Math.max(p.plot.pulse||0,1);});}
function mycelPrimaryContact(s,k){
  if(coopGuest()||!s||s.kind!=='spore'||!mycelId(s.primarySerial)||s.initialRewardConsumed||s.world!==worldLevel()||classShots.indexOf(s)<0||!k||k.hp<=0||floatKrek.indexOf(k)<0||enemyDistance(k,s.x,s.y)>8||!combatLineClear(s.x,s.y,k.x,k.y))return false;
  var m=coop?coop.members[s.owner]:null;if(coop?(!m||m.left||m.classId!=='herbalist'):s.owner!==''||rogueRun.classId!=='herbalist')return false;var q=mycelRefreshClocks(m),b=s.build=mycelCleanBuild(s.build||s.perks),point={x:s.x,y:s.y},linked=mycelNetwork(m),threat=b.symphony?linked.filter(function(p){return p.plot.health>=.75&&p.plot.moisture>=.30;}).map(function(p){return mycelThreat(k,p.plot);}).find(Boolean):null;
  s.initialRewardConsumed=1;q.culture=Math.min(6,q.culture+.5);if(!k.combatId)k.combatId=++classPestId;s.seenIds=[k.combatId];s.hits=1;var dead=combatDamage(k,1+.2*b.ferment,s.x-s.vx*.1,b);
  if(threat&&mechBombInterrupted(k,threat,dead)){q.chorusSerial=s.primarySerial;q.chorusPlantId=threat.plant.id;mycelSetTimer(q,'chorusT',4);}
  mycelSymbiosis(q,s);var anchor=mycelPlotsAt(point,58,true).length>0||q.clouds.some(function(c){return c.world===worldLevel()&&mycelAge(c,6)<c.life&&mycelContactPoint(c,point,44);}),links=(anchor?1:0)+(b.outbreak?2:0),previous=k,range=38+5*b.colony;
  for(var i=0;i<links;i++){var next=floatKrek.filter(function(n){return n.hp>0&&!s.seenIds.includes(n.combatId)&&enemyDistance(n,previous.x,previous.y)<=range&&combatLineClear(previous.x,previous.y,n.x,n.y);}).sort(function(a,c){return enemyDistance(a,previous.x,previous.y)-enemyDistance(c,previous.x,previous.y)||(a.combatId||0)-(c.combatId||0);})[0];if(!next)break;if(!next.combatId)next.combatId=++classPestId;s.seenIds.push(next.combatId);combatDamage(next,.65*(1+.2*b.ferment),previous.x,b);combatFx('mycel-chain',next.x,next.y,7,1);previous=next;}
  combatObjectives(s.x,s.y,9);combatFx('mycel-dart',s.x,s.y,7,Math.sign(s.vx));return true;
}
function mycelCloudWorld(aim,tag){var m=mycelMember();if(coopGuest()||!mycelCanAct(m,'cloud'))return false;var q=mycelRefreshClocks(m),place=mycelCloudPlacement(aim,m),active=q.clouds.filter(function(c){return c.world===worldLevel()&&mycelAge(c,6)<c.life;});if(q.cloudCool>0||q.culture<2||active.length>=2||!place.valid)return false;var serial=mycelNextSerial(),b=mycelBuild(m);q.culture-=2;q.clouds=active;var c={serial:serial,startTag:mycelId(tag)||serial,world:worldLevel(),x:place.x,y:place.y,age:0,life:3+b.ferment,pulseMask:0,build:b};q.clouds.push(mycelBindClock(c,0));mycelSetTimer(q,'cloudCool',5);mycelWake(m);mycelCue(q,'cloud',serial,c.startTag,mycelActor(m).face);P.secondaryCool=5;combatFx('mycel-cloud',c.x,c.y,44,mycelActor(m).face);return true;}
function mycelObjectiveUseful(point,r){return typeof mycelObjectivePoints==='function'?mycelObjectivePoints(point,r).length>0:runHazards.some(function(h){return h.type==='spore'&&h.tell>0&&mycelContactPoint(point,hazardPosition(h),r);});}
function mycelAllies(cast,m){if(!lastSeedMode())return [];return seedActors().filter(function(a){return mycelOwner(a.member)!==mycelOwner(m)&&a.v.hp>0&&a.v.hp<100&&mycelContactPoint(cast,{x:a.p.x,y:a.p.y-12},48);}).sort(function(a,b){return (a.member?a.member.slot:0)-(b.member?b.member.slot:0)||a.id.localeCompare(b.id);});}
function mycelBloomUseful(cast,m){return floatKrek.some(function(k){return k.hp>0&&!(k.bossId==='hollow-crown'&&!k.tideBoss&&(k.crownTransition>0||k.phase===2))&&enemyDistance(k,cast.x,cast.y)<=48&&combatLineClear(cast.x,cast.y,k.x,k.y);})||mycelPlotsAt(cast,48,true).some(function(p){return p.plot.health<1||p.plot.moisture<1;})||!relicRunMode()&&mycelPlotsAt(cast,48,false).some(function(p){return p.plot.dead>0&&p.plot.dead<=8;})||mycelAllies(cast,m).length>0||mycelObjectiveUseful(cast,48);}
function mycelBloomWorld(tag){var m=mycelMember();if(coopGuest()||!mycelCanAct(m,'bloom'))return false;var q=mycelRefreshClocks(m),a=mycelActor(m),point={x:a.x,y:a.y-12};if(q.specialCool>0||q.culture<4||q.bloom&&q.bloom.age<4&&!q.bloom.cancelled||!mycelBloomUseful(point,m))return false;var serial=mycelNextSerial(),stub=!relicRunMode()?mycelPlotsAt(point,48,false).filter(function(p){return p.plot.dead>0&&p.plot.dead<=8;}).sort(function(a,b){return b.plot.dead-a.plot.dead||a.id-b.id;})[0]:null,c={serial:serial,startTag:mycelId(tag)||serial,world:worldLevel(),x:point.x,y:point.y,age:0,pulseMask:0,cancelled:0,readied:0,build:mycelBuild(m),chorusPulse:q.chorusT>0?1:0,reviveId:stub?stub.id:0,reviveKind:stub?stub.plot.kind:0,reviveSeed:stub?stub.plot.seed>>>0:0,reviveConsumed:0,plots:[],allies:[],hpUsed:0};q.culture-=4;if(c.chorusPulse)mycelSetTimer(q,'chorusT',0);q.bloom=mycelBindClock(c,0);mycelSetTimer(q,'specialCool',12);mycelWake(m);mycelCue(q,'bloom',serial,c.startTag,a.face);P.skillCool=12;combatFx('mycel-bloom',c.x,c.y,48,a.face);return true;}
function mycelTargetPulse(k,cast,kind,slot){var owner=mycelCastOwner(cast);if(!owner)return false;var field=kind==='cloud'?'mycelCloudEvents':'mycelBloomEvents',max=kind==='cloud'?8:4,events=mycelRestorePestEvents(k)[field],row=events.find(function(e){return e.owner===owner.owner&&e.serial===cast.serial&&e.world===cast.world;});k[field]=events;if(!row){if(events.length>=max)return false;row={owner:owner.owner,serial:cast.serial,world:cast.world,mask:0};events.push(row);}var bit=1<<slot;if(row.mask&bit)return false;row.mask|=bit;return true;}
function mycelPulse(m,cast,kind,slot){var bit=1<<slot;if(cast.pulseMask&bit)return false;cast.pulseMask|=bit;var ctx=mycelRestoreContext(cast),r=kind==='cloud'?44:48,damage=kind==='cloud'?.25:.8*(1+.2*cast.build.ferment)*(slot===0&&cast.chorusPulse?1.25:1),useful=false;mycelOwned(m,function(){var seen=[];floatKrek.slice().forEach(function(k){if(k.hp<=0||enemyDistance(k,cast.x,cast.y)>r||!combatLineClear(cast.x,cast.y,k.x,k.y))return;if(!k.combatId)k.combatId=++classPestId;if(seen.includes(k.combatId)||!mycelTargetPulse(k,cast,kind,slot))return;seen.push(k.combatId);var hp=k.hp,windup=k.windup;combatDamage(k,damage,cast.x,cast.build,ctx);if(k.hp<hp||windup>0&&!k.windup)useful=true;});combatObjectives(cast.x,cast.y,r,ctx);});
  if(kind==='bloom'){
    if(cast.reviveId&&!cast.reviveConsumed){cast.reviveConsumed=1;var stub=gardenPlots.find(function(p){return p.id===cast.reviveId&&p.kind===cast.reviveKind&&(p.seed>>>0)===cast.reviveSeed&&p.dead>0&&p.dead<=8;});if(stub&&!relicRunMode()&&mycelContactPoint(cast,mycelPlantPoint(stub,cast),48)){var fallenLeft=stub.dead;stub.dead=0;var revived=mycelRestoreCast(cast,stub,.04,.05);if(revived.health>0&&stub.health>0){stub.hit=0;useful=true;}else stub.dead=fallenLeft;}}
    mycelPlotsAt(cast,48,true).forEach(function(p){var revived=p.id===cast.reviveId&&cast.reviveConsumed&&slot===0;if(revived)return;var delivered=mycelRestoreCast(cast,p.plot,.04,.05);if(delivered.health||delivered.water)useful=true;});
    var hpBudget=Math.min(4,12-cast.hpUsed);mycelAllies(cast,m).forEach(function(a){if(hpBudget<=0)return;var row=cast.allies.find(function(p){return p.id===a.id;});if(!row){if(cast.allies.length>=4)return;row={id:a.id,usedHP:0};cast.allies.push(row);}var amount=Math.min(hpBudget,100-a.v.hp);row.usedHP+=amount;cast.hpUsed+=amount;hpBudget-=amount;a.v.hp+=amount;if(amount>0)useful=true;});
    if((useful||ctx.useful)&&cast.build.symphony&&!cast.readied){cast.readied=1;mycelSetTimer(mycelState(m),'primaryCool',0);if(mycelLocal(m))bombCool=0;else if(m)m.cool=performance.now();}
  }
  combatFx(kind==='cloud'?'mycel-cloud':'mycel-bloom',cast.x,cast.y,r,1);return useful||ctx.useful;
}
function mycelSlowFactor(k){if(!k||!(k.hp>0))return 1;var slow=1;mycelOwners().forEach(function(m){if(m&&m.left||mycelClass(m)!=='herbalist')return;var q=mycelPeek(m);if(q&&q.clouds.some(function(c){return c.world===worldLevel()&&mycelAge(c,6)<c.life&&enemyDistance(k,c.x,c.y)<=44&&combatLineClear(c.x,c.y,k.x,k.y);}))slow=Math.min(slow,k.boss||k.guardianStage?.9:.7);});return slow;}
function mycelDriftWorld(aim,tag){
  var m=mycelMember();if(coopGuest()||!mycelCanAct(m,'drift'))return false;var q=mycelRefreshClocks(m);if(q.utilityCool>0)return false;var a=mycelActor(m),face=aim&&Number.isFinite(aim.x)&&Math.abs(aim.x-a.x)>.01?aim.x<a.x?-1:1:a.face<0?-1:1,vy=a.grounded?-90:Math.max(-90,Math.min(0,a.vy||0)),serial=mycelNextSerial(),d={serial:serial,startTag:mycelId(tag)||serial,world:worldLevel(),phase:1,face:face,originX:a.x,originY:a.y,x:a.x,y:a.y,vx:face*100,vy:vy,launchVY:vy,riseLimit:vy*vy/(2*430),riseUsed:0,apexY:a.y,age:0,totalAge:0,travel:0,seenAir:a.grounded?0:1,landingLease:.8,landingConsumed:0,landingPlantId:0};q.drift=mycelBindClock(d,0);mycelSetTimer(q,'utilityCool',6);mycelWake(m);
  var launch=typeof mycelLaunchPose==='function'?mycelLaunchPose(a,d):Object.assign({},a,{vx:face*100,vy:vy,grounded:false,platform:null,st:'free',coyote:0,held:false,land:0});Object.assign(a,launch);if(m&&coop&&m.id!==coop.me){Object.assign(m.avatar,launch);if(typeof coopMycelCorrect==='function')coopMycelCorrect(m,m.avatar,'accepted-cast');}if(mycelLocal(m)){P.mycelAppliedLaunchSerial=serial;P.utilityCool=6;jumpBuf=0;task=holdWater=null;}combatFx('mycel-drift',a.x,a.y-8,8,face);return true;
}
function mycelMotionIntent(m,dt){m=mycelMember(m);var q=mycelPeek(m),d=q&&q.drift?mycelCaptureDrift(q.drift):null,cancelled=mycelLocal(m)&&coopGuest()&&P.mycelCancelledCasts&&P.mycelCancelledCasts.drift===d?.serial;if(!d||!d.phase||d.world!==worldLevel()||cancelled)return {kind:'none',serial:0,world:worldLevel(),phase:0,overrideX:false,overrideY:false,maxDistance:0,remainingPath:0};var active=d.phase===1,remaining=Math.max(0,48-d.travel);return {kind:active?'drift':'none',serial:d.serial,world:d.world,phase:d.phase,vx:d.face*100,vy:d.vy,overrideX:active,overrideY:false,maxDistance:active?Math.min(remaining,182*Math.min(Number.isFinite(dt)?Math.max(0,dt):1/120,.35-d.age)):0,remainingPath:remaining,launchVY:d.launchVY};}
function mycelMovement(m,before,after,dt,context){
  m=mycelMember(m);context=context||{};var q=mycelPeek(m),d=q&&q.drift;if(coopGuest()||!d||!d.phase||d.world!==worldLevel()||context.world!==d.world||context.serial!==d.serial||!['physics','network'].includes(context.source)||!(dt>0)||!before||!after)return false;
  var distance=Number.isFinite(context.path)?context.path:Math.hypot(after.x-before.x,after.y-before.y),active=context.kind==='drift'||context.phase==='active'||Number.isFinite(context.age1)&&context.age1<=.35+1e-8;var rise=Math.max(0,before.y-after.y);if(distance<0||active&&distance>182*dt+1e-6||active&&distance>48-d.travel+1e-6||rise>d.riseLimit-d.riseUsed+1e-5)return false;
  if(!mycelPresent(m)||mycelWetBody(after,m)){mycelCancelMotion(m,'water');return false;}if(active)d.travel=Math.min(48,d.travel+distance);d.x=after.x;d.y=after.y;d.vx=after.vx||0;d.vy=after.vy||0;d.riseUsed=Math.min(d.riseLimit,d.riseUsed+rise);d.apexY=Math.min(d.apexY,after.y);if(!after.grounded&&!context.placed)d.seenAir=1;if(context.source==='physics'&&active&&dt>0&&distance<=1e-7)d.phase=2;return true;
}
function mycelLanding(m,support,before,after,context){m=mycelMember(m);context=context||{};var q=mycelPeek(m),d=q&&q.drift;if(coopGuest()||!d||!d.phase||d.landingConsumed||!d.seenAir||mycelAge(d,1.15)>=1.15||d.world!==worldLevel()||context.world!==d.world||context.serial!==d.serial||!['physics','network'].includes(context.source)||!before||before.grounded||!after||!after.grounded||before.vy<-.01||!cairnSupportPoint(after.x,after.y,support&&support.id||after.platform||null))return false;
  d.landingConsumed=1;d.landingLease=0;if(d.phase===2)d.phase=0;if(context.canContact===false||context.placed||context.corrected&&context.source!=='network'||!mycelPresent(m)||mycelWetBody(after,m))return false;var plant=mycelNetwork(m,{x:after.x,y:after.y-12})[0];if(!plant)return false;var amount=Math.max(0,Math.min(.04,1-plant.plot.moisture));d.landingPlantId=plant.id;plant.plot.moisture+=amount;if(amount>0){plant.plot.pulse=Math.max(plant.plot.pulse||0,1);combatFx('mycel-landing',plant.x,plant.y,8,after.face||d.face);}return amount>0;
}
function mycelCancelMotion(m,reason){m=mycelMember(m);var q=mycelPeek(m);if(!q||!q.drift)return false;if(coopGuest()){if(mycelLocal(m)){P.mycelCancelledCasts=Object.assign({},P.mycelCancelledCasts,{drift:q.drift.serial});}return false;}q.drift.phase=0;q.drift.landingConsumed=1;q.drift.landingLease=0;return true;}
function mycelDriftCancelWorld(startTag){if(coopGuest())return false;var m=mycelMember(),q=mycelPeek(m);return !!(q&&q.drift&&q.drift.phase&&q.drift.startTag===mycelId(startTag)&&mycelCancelMotion(m,'cancel'));}
function mycelTag(field){P[field]=(P[field]||0)+1;var m=mycelMember();if(m)m[field]=Math.max(m[field]||0,P[field]);return P[field];}
function mycelPredict(verb,tag,cool){mycelWake(mycelMember());P['mycel'+verb[0].toUpperCase()+verb.slice(1)+'Input']={tag:tag,startTag:tag,phase:'start'};if(verb==='primary')bombCool=bombCoolMax=cool;else P[verb==='cloud'?'secondaryCool':verb==='drift'?'utilityCool':'skillCool']=cool;}
function mycelPrimary(aim){var m=mycelMember();if(coopGuest()&&bombCool>0)return false;if(!mycelCanAct(m,'primary')||mycelRemaining(mycelPeek(m)||{},'primaryCool')>0)return false;aim=combatAim(aim);var tag=mycelTag('attackTag');if(!coopGuest())return mycelPrimaryWorld(aim,tag);if(!coopAction('throw',{x:aim.x,y:aim.y,spore:aim.spore||0,attackTag:tag}))return false;mycelPredict('primary',tag,mycelPrimaryInterval(m));return true;}
function mycelCloud(aim){var m=mycelMember(),q=mycelPeek(m)||{};if(coopGuest()&&P.secondaryCool>0)return false;if(!mycelCanAct(m,'cloud')||mycelRemaining(q,'cloudCool')>0||!(q.culture>=2)||!mycelCloudPlacement(aim,m).valid||(q.clouds||[]).filter(function(c){return c.world===worldLevel()&&mycelAge(c,6)<c.life;}).length>=2)return false;var tag=mycelTag('secondaryTag');if(!coopGuest())return mycelCloudWorld(aim,tag);if(!coopAction('secondary',{x:aim.x,y:aim.y,secondaryTag:tag}))return false;mycelPredict('cloud',tag,5);return true;}
function mycelDrift(aim){var m=mycelMember();if(coopGuest()&&P.utilityCool>0)return false;if(!mycelCanAct(m,'drift')||mycelRemaining(mycelPeek(m)||{},'utilityCool')>0)return false;aim=combatAim(aim);var tag=mycelTag('utilityTag');if(!coopGuest())return mycelDriftWorld(aim,tag);if(!coopAction('utility',{phase:'start',x:aim.x,y:aim.y,utilityTag:tag}))return false;mycelPredict('drift',tag,6);return true;}
function mycelBloom(){var m=mycelMember(),q=mycelPeek(m)||{},a=mycelActor(m);if(coopGuest()&&P.skillCool>0)return false;if(!mycelCanAct(m,'bloom')||mycelRemaining(q,'specialCool')>0||!(q.culture>=4)||!mycelBloomUseful({x:a.x,y:a.y-12},m))return false;var tag=mycelTag('skillTag');if(!coopGuest())return mycelBloomWorld(tag);if(!coopAction('skill',{phase:'start',x:a.x,y:a.y,skillTag:tag}))return false;mycelPredict('bloom',tag,12);return true;}
function mycelInterrupt(reason){if(ownClass().id!=='herbalist')return false;var m=mycelMember(),q=mycelPeek(m),input=P.mycelDriftInput,start=input&&input.phase==='start'?input.startTag:q&&q.drift&&q.drift.startTag;if(coopGuest()){if(mycelId(start)){var tag=mycelTag('utilityTag');if(!coopAction('utility',{phase:'cancel',utilityTag:tag,startTag:start}))return false;P.mycelDriftInput={tag:tag,startTag:start,phase:'cancel'};}P.mycelCancelledCasts=Object.assign({},P.mycelCancelledCasts,{drift:q&&q.drift&&q.drift.serial||0});return !!start;}return mycelCancelMotion(m,reason);}
function mycelRetire(q){q.clouds=[];q.bloom=q.drift=null;q.networkIds=[];q.symbiosis=[];q.primaryPoseT=q.cloudPoseT=q.bloomPoseT=0;}
function updateMycelCombat(dt){
  if(runIsPaused())return;mycelOwners().forEach(function(m){var q=mycelPeek(m);if(!q&&mycelClass(m)!=='herbalist')return;q=mycelRefreshClocks(m);if((m&&m.left)||mycelClass(m)!=='herbalist'||q.world!==worldLevel()){mycelRetire(q);q.world=worldLevel();classShots=classShots.filter(function(s){return s.kind!=='spore'||s.owner!==mycelOwner(m);});return;}if(coopGuest())return;
    var present=mycelPresent(m),a=mycelActor(m);var links=mycelNetwork(m);q.networkIds=links.map(function(p){return p.id;});if(present){var wet=mycelPlotsAt({x:a.x,y:a.y-12},58,true).filter(function(p){return p.wet;}).length;q.culture=Math.min(6,q.culture+.5*Math.min(2,wet)*Math.max(0,Math.min(.1,dt)));}
    if(!present){mycelCancelMotion(m,'state');if(q.bloom&&!q.bloom.cancelled){q.bloom.cancelled=1;q.bloom.pulseMask=7;}}
    q.clouds.forEach(function(c){if(c.world!==worldLevel())return;for(var slot=0;slot<3;slot++)if(c.age>=slot+1-1e-8&&!(c.pulseMask&(1<<slot)))mycelPulse(m,c,'cloud',slot);});q.clouds=q.clouds.filter(function(c){return c.world===worldLevel()&&c.age<c.life-1e-8;});
    var b=q.bloom;if(b&&!b.cancelled){for(var slot=0;slot<3;slot++)if(b.age>=slot*2-1e-8&&!(b.pulseMask&(1<<slot)))mycelPulse(m,b,'bloom',slot);}if(b&&b.age>=5.6-1e-8)q.bloom=null;
    if(mycelLocal(m)){P.secondaryCool=q.cloudCool;P.utilityCool=q.utilityCool;P.skillCool=q.specialCool;}
  });
}
