const {test}=require('node:test');
const assert=require('node:assert/strict');
const {loadGame,plot}=require('./game-harness.cjs');
// These isolated Cairn fixtures use the original un-authored terrain baseline.
function fresh(mode){const h=loadGame({__levelData:{gardens:{}}}),g=h.game;g.resetRogueRun('Cairn',{classId:'bulwark',skinId:'ember',difficulty:'medium',...(mode?{mode}:{})});g.floatKrek=[];g.gardenPlots=[];g.runHazards=[];g.stageLayout().platforms=[];g.stageLayout().ladders=[];Object.assign(g.P,{x:200,y:g.surfaceY(200),grounded:true,vx:0,vy:0,face:1,st:'free',wet:false,platform:null,dodgeT:0,tun:0,pounce:0});return h;}
function close(a,b){assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);}
function tick(h,s,hz=60){for(let i=0;i<Math.round(s*hz);i++){h.advance(1000/hz);h.game.updateCairnCombat(1/hz);}}
function pest(g,fields={}){const k=Object.assign(g.makeKrek(1,false,1),{x:g.P.x+20,y:g.P.y-12,hp:100,maxHp:100,scout:false,raid:true,queen:false,boss:false,elite:false,face:-1},fields);g.floatKrek.push(k);return k;}
function attack(g,k,kind='strike',p){assert.ok(g.cairnBeginAttack(k));return g.cairnContact(k,{kind,pointX:p?p.x:g.P.x,pointY:p?g.surfaceY(p.x):g.P.y-12,plantId:p?p.id:0,accepted:true});}
function hit(h,k){const g=h.game;assert.equal(g.cairnPrimaryWorld(k),true);tick(h,.22,100);}
function idle(h,seconds){for(let i=0;i<Math.round(seconds*120);i++){h.advance(1000/120);h.game.updatePlayer(1/120,{axis:0,top:48});}}

test('real automatic lantern idle wakes only on an accepted Cairn action and preserves denied/manual poses',()=>{
 for(const key of ['b','c','v','e']){const h=fresh(),g=h.game,q=g.cairnState();idle(h,7.1);assert.equal(g.P.st,'lampUp');assert.equal(g.P.autoIdlePose,true);const pose=g.P.anim;assert.equal(g.cairnStone({x:g.P.x+50,y:g.P.y-12}),false);assert.equal(g.P.st,'lampUp');assert.equal(g.P.anim,pose);assert.equal(g.P.autoIdlePose,true);q.strata=3;const serial=g.cairnSerial;g.cairnPhasePolicy();g.cairnRidgePlacement();assert.equal(g.P.st,'lampUp');assert.equal(g.P.autoIdlePose,true);assert.equal(g.cairnSerial,serial);h.key('keydown',key);h.key('keyup',key);assert.equal(g.P.st,'free',key);assert.equal(g.P.autoIdlePose,false,key);assert.equal(g.P.still,0);assert.equal(key==='b'?q.primaryPhase:key==='c'?q.stonePhase:key==='v'?q.braceT:q.ridgePhase,key==='v'?3:1);}
 const denied=fresh(),d=denied.game;idle(denied,7.1);d.rogueRun.cairn=d.cairnRestoreState({strata:3,primaryCool:1,stoneCool:1,utilityCool:1,specialCool:1});for(const cast of [()=>d.cairnPrimary({x:d.P.x+20,y:d.P.y-12}),()=>d.cairnStone({x:d.P.x+20,y:d.P.y-12}),()=>d.cairnBrace(),()=>d.cairnBreakwater()]){assert.equal(cast(),false);assert.equal(d.P.st,'lampUp');assert.equal(d.P.autoIdlePose,true);assert.equal(d.cairnState().strata,3);}d.rogueRun.cairn=d.cairnRestoreState({strata:3});d.stageLayout().ladders=[{x:d.P.x+48,w:14,top:d.P.y-30,bottom:d.P.y}];assert.equal(d.cairnBreakwater(),false);assert.equal(d.P.st,'lampUp');assert.equal(d.P.autoIdlePose,true);assert.equal(d.cairnState().ridgeReserved,0);
 const manual=fresh(),g=manual.game,q=g.cairnState();q.strata=3;g.lampToggle=true;idle(manual,.01);assert.equal(g.P.st,'lampUp');assert.equal(g.P.autoIdlePose,false);for(const cast of [()=>g.cairnPrimary({x:g.P.x+20,y:g.P.y-12}),()=>g.cairnStone({x:g.P.x+20,y:g.P.y-12}),()=>g.cairnBrace(),()=>g.cairnBreakwater()]){assert.equal(cast(),false);assert.equal(g.P.st,'lampUp');assert.equal(q.strata,3);}
 const rest=fresh(),r=rest.game;idle(rest,7.1);r.P.still=27;r.P.done=true;idle(rest,1/120);assert.equal(r.P.st,'lamp');idle(rest,1/120);assert.equal(r.P.st,'lampDn');r.P.done=true;idle(rest,1/120);assert.equal(r.P.st,'toSit');r.P.done=true;idle(rest,1/120);assert.equal(r.P.st,'rest');assert.equal(r.P.autoIdlePose,true);assert.equal(r.cairnBrace(),true);assert.equal(r.P.st,'free');assert.equal(r.P.autoIdlePose,false);
});

test('Three Stone accepts1.15 s interval, fixed .22 startup/.3 recovery and only confirmed chain steps',()=>{
 for(const hz of [30,60,120]){const h=fresh(),g=h.game,q=g.cairnState(),k=pest(g);assert.equal(g.cairnPrimaryWorld(k,1),true);close(k.hp,100);h.advance(219);g.updateCairnCombat(.219);close(k.hp,100);h.advance(1);g.updateCairnCombat(.001);close(k.hp,99);assert.equal(q.primaryConsumed,1);assert.equal(q.combo,1);assert.equal(q.contactRemainder,1);close(q.primaryRecovery,.3);assert.equal(g.cairnPrimaryWorld(k,2),false);tick(h,.3,hz);assert.equal(q.primaryPhase,0);assert.equal(g.cairnPrimaryWorld(k,2),false);h.advance(630);g.updateCairnCombat(.1);assert.equal(g.cairnPrimaryWorld(k,2),true);tick(h,.22,100);close(k.hp,98);assert.equal(q.combo,2);h.advance(930);g.updateCairnCombat(.1);k.y=g.P.y-5;assert.equal(g.cairnPrimaryWorld(k,3),true);tick(h,.22,100);close(k.hp,96.65);assert.equal(q.combo,0);assert.equal(q.strata,1);assert.equal(q.contactRemainder,0);g.updateCairnCombat(.1);close(k.hp,96.65);}
 const h=fresh(),g=h.game,q=g.cairnState();assert.equal(g.cairnPrimaryWorld({x:g.P.x+100,y:g.P.y-12},1),true);tick(h,.22,100);assert.equal(q.combo,0);assert.equal(q.comboT,0);assert.equal(q.strata,0);assert.equal(q.contactRemainder,0);
});
test('primary reach/front/LOS and every-third action resource do not scale with target count',()=>{
 const h=fresh(),g=h.game,q=g.cairnState(),a=pest(g,{x:g.P.x+32}),b=pest(g,{x:g.P.x+33}),back=pest(g,{x:g.P.x-8});hit(h,a);close(a.hp,99);close(b.hp,100);close(back.hp,100);assert.equal(q.contactRemainder,1);
 const m=fresh(),v=m.game,x=v.cairnState();for(let i=0;i<4;i++)pest(v,{x:v.P.x+10+i});hit(m,v.floatKrek[0]);assert.equal(x.contactRemainder,1);assert.equal(x.strata,0);
 const wall=fresh(),w=wall.game,s=w.cairnState(),target=pest(w);w.stageLayout().platforms.push({id:'wall',x:w.P.x+8,y:w.P.y-30,w:2,h:40,solid:true});hit(wall,target);close(target.hp,100);assert.equal(s.contactRemainder,0);
});
test('heavy ram, elite and guardian contacts take damage without hard windup or charge interruption',()=>{
 for(const fields of [{kind:11,chargeT:.46},{elite:true},{guardianStage:8,pattern:'dash'},{boss:true,finalBoss:false}]){const h=fresh(),g=h.game,k=pest(g,{...fields,windup:.6,vx:30,vy:0});hit(h,k);assert.ok(k.hp<100);assert.equal(k.windup,.6);assert.equal(k.flee,0);assert.equal(k.vx,30);if(fields.chargeT)assert.equal(k.chargeT,.46);}
});
test('airborne third is denied unpaid, first two can jump during accepted startup, expiry returns to sweep',()=>{
 const h=fresh(),g=h.game,k=pest(g);g.rogueRun.cairn=g.cairnRestoreState({combo:2,comboT:2.4,primaryWorld:g.rogueRun.world});const q=g.cairnState();g.P.grounded=false;assert.equal(g.cairnPrimaryWorld(k,1),false);assert.equal(q.primaryCool,0);assert.equal(q.primarySerial,0);assert.equal(g.classAttackCooldown()>.7,true);
 q.combo=0;assert.equal(g.cairnPrimaryWorld(k,2),true);assert.equal(g.cairnPhasePolicy().blockJump,false);g.P.y-=2;tick(h,.22,100);close(k.hp,99);assert.equal(q.combo,1);tick(h,2.5,100);g.P.grounded=true;g.P.y=g.surfaceY(g.P.x);assert.equal(g.cairnPrimaryWorld(k,3),true);assert.equal(q.primaryStep,0);
});
test('shared bite gate holds at most one third-contact opportunity until a later genuine primary',()=>{
 const h=fresh(),g=h.game,q=g.cairnState(),p=plot({id:41,x:g.P.x+12}),k=pest(g);g.gardenPlots=[p];const e=attack(g,k,'bite',p),d=g.cairnProtection(p,{kind:'bite',pointX:p.x,pointY:g.surfaceY(p.x)});p.health=.93;assert.equal(g.cairnReducedBite(d,e,{health:1,rawDamage:.1},{health:.93}),true);assert.equal(q.strata,1);q.contactRemainder=2;hit(h,k);assert.equal(q.strata,1);assert.equal(q.contactPending,1);tick(h,2,100);assert.equal(q.strata,1);assert.equal(q.contactPending,1);hit(h,k);assert.equal(q.strata,2);assert.equal(q.contactPending,0);assert.equal(q.contactRemainder,0);
});
test('reaching cap through a later bite discards pending completed contacts before a Stone spend',()=>{
 const h=fresh(),g=h.game,q=g.cairnState(),p=plot({id:45,x:g.P.x+10}),k=pest(g);g.gardenPlots=[p];q.strata=1;const defense=g.cairnProtection(p,{kind:'bite'});let e=attack(g,k,'bite',p);p.health=.93;assert.equal(g.cairnReducedBite(defense,e,{health:1,rawDamage:.1},{health:.93}),true);assert.equal(q.strata,2);q.contactRemainder=2;hit(h,k);assert.equal(q.contactPending,1);tick(h,1.5,100);e=attack(g,k,'bite',p);assert.equal(g.cairnReducedBite(defense,e,{health:1,rawDamage:.1},{health:.93}),true);assert.equal(q.strata,3);assert.equal(q.contactPending,0);assert.equal(q.contactRemainder,0);assert.equal(g.cairnStoneWorld(k,7),true);assert.equal(q.strata,2);tick(h,1.5,100);hit(h,k);assert.equal(q.strata,2);assert.equal(q.contactRemainder,1);
});
test('third knuckle routes to the actual target foot and cannot bridge an unsupported airborne target',()=>{
 const h=fresh(),g=h.game,k=pest(g,{x:g.P.x+20,y:g.P.y-12}),ground=pest(g,{x:g.P.x+22,y:g.P.y-5});g.rogueRun.cairn=g.cairnRestoreState({combo:2,comboT:2.4,primaryWorld:g.rogueRun.world});assert.equal(g.cairnPrimaryWorld(k,1),true);tick(h,.22,100);close(k.hp,100);close(ground.hp,98.65);assert.equal(g.cairnState().combo,0);
});
test('C spends once, follows low physical arc and leaves one3s patch only after real enemy contact',()=>{
 for(const hz of [30,60,120]){const h=fresh(),g=h.game,q=g.cairnState(),k=pest(g,{x:g.P.x+30,y:g.P.y-16});q.strata=2;assert.equal(g.cairnStoneWorld(k,1),true);assert.equal(q.strata,1);close(q.stoneCool,5);assert.equal(g.cairnStoneWorld(k,2),false);tick(h,.5,hz);close(k.hp,98.6);assert.equal(q.stoneContactConsumed,1);assert.equal(q.stonePhase,2);assert.ok(q.stoneTravel<=72);const serial=q.stoneSerial;tick(h,.5,hz);close(k.hp,98.6);assert.equal(q.stoneSerial,serial);tick(h,3,hz);assert.equal(q.stonePhase,0);}
 for(const stop of ['empty','rock']){const h=fresh(),g=h.game,q=g.cairnState(),k=pest(g,{x:g.P.x+40,y:g.P.y-16});q.strata=1;if(stop==='empty')g.floatKrek=[];else g.stageLayout().platforms.push({id:'wall',x:g.P.x+18,y:g.P.y-35,w:2,h:45,solid:true});assert.equal(g.cairnStoneWorld(k,1),true);tick(h,1,120);close(k.hp,100);assert.equal(q.strata,0);assert.equal(q.stonePhase,0);assert.equal(q.patchT,0);assert.equal(q.stoneContactConsumed,0);}
});
test('Brace is defense alone; only one real frontal contact in first .28s counters and preserves incoming damage',()=>{
 for(const kind of ['front','rear','late','dodge']){const h=fresh('last-seed'),g=h.game,q=g.cairnState(),k=pest(g,{x:g.P.x+(kind==='rear'?-20:20)}),v=g.seedVital();v.hp=100;assert.equal(g.cairnBraceWorld(7),true);close(k.hp,100);if(kind==='late')h.advance(280);if(kind==='dodge')g.P.dodgeT=.1;const e=attack(g,k);assert.equal(g.damageGardener(null,10,null,e),kind!=='dodge');if(kind==='front'){close(k.hp,98.5);assert.equal(q.parryConsumed,1);close(q.utilityCool,2.5);close(v.hp,96.5);assert.equal(g.cairnStrike(null,e),false);}else{close(k.hp,100);assert.equal(q.parryConsumed,0);}assert.equal(q.strata,0);}
});
test('exact source-family consumption survives a new enemy attack, old hazard, and dead attacker',()=>{
 const h=fresh(),g=h.game,k=pest(g),p=plot({id:9,x:g.P.x+10}),q=g.cairnState();g.gardenPlots=[p];const e=attack(g,k,'bite',p),hazard=g.addRunHazard('gust',k.x,k.y,12,0,.3,{power:1});assert.equal(g.cairnTagHazard(hazard,k,'strike'),true);p.health=.93;const defense=g.cairnProtection(p,{kind:'bite'});assert.equal(g.cairnReducedBite(defense,e,{health:1,rawDamage:.1},{health:.93}),true);assert.equal(hazard.cairnBiteUsed,1);const old=hazard.cairnAttackSerial;attack(g,k);assert.notEqual(k.cairnAttackSerial,old);h.advance(1600);g.updateCairnCombat(.1);const older=g.cairnContact(hazard,{kind:'bite',plantId:p.id,pointX:p.x,pointY:g.surfaceY(p.x)});assert.equal(g.cairnReducedBite(defense,older,{health:1,rawDamage:.1},{health:.93}),false);assert.equal(q.strata,1);g.floatKrek=[];assert.equal(g.cairnConsumeAttack(older,'bite'),false);assert.equal(g.cairnConsumeAttack(older,'parry'),true);assert.equal(hazard.cairnParryUsed,1);
});
test('pure guard queries allocate no state/IDs and strongest Sligo blocks weaker Cairn credit',()=>{
 const h=fresh(),g=h.game,p=plot({id:8,x:g.P.x+10});g.gardenPlots=[p];assert.equal(g.cairnPeek(),null);const serial=g.cairnSerial,attackSerial=g.cairnAttackSerial;for(let i=0;i<3;i++){close(g.cairnProtection(p,{kind:'bite'}).fraction,.3);g.cairnPhasePolicy();g.cairnBraceActive();g.cairnRidgePlacement();}assert.equal(g.cairnPeek(),null);assert.equal(g.cairnSerial,serial);assert.equal(g.cairnAttackSerial,attackSerial);
 const network={host:true,user:{id:'cairn'},room:{id:'g',host:'cairn',members:[{id:'cairn',slot:1},{id:'sligo',slot:2}]},loadouts:{cairn:{classId:'bulwark',skinId:'ember'},sligo:{classId:'sligo',skinId:'sligo'}},sendInput(){},sendState(){},tick(){}};g.beginCoop(network);p.x=g.P.x+10;const s=g.coop.members.sligo;s.avatar.x=g.P.x+10;s.avatar.y=g.P.y;s.avatar.grounded=true;s.avatar.wet=false;s.tunUntil=20000;s.tunX=s.avatar.x;const d=g.cairnProtection(p,{kind:'bite'});close(d.fraction,.5);assert.equal(d.sourceKind,'sligo-tun');
});
test('root absorption debits original brace remaining once without resetting parry age',()=>{
 const h=fresh(),g=h.game,q=g.cairnState();assert.equal(g.cairnBraceWorld(8),true);h.advance(100);g.updateCairnCombat(.1);const root=g.addRunHazard('root',g.P.x,10,0,1,g.P.x,g.P.y,g.P.y);assert.equal(g.rootAbsorb(root),true);close(q.braceT,1.9);close(q.braceAge,.1);assert.equal(g.rootAbsorb(root),true);close(q.braceT,1.9);const k=pest(g),e=attack(g,k);assert.equal(g.cairnStrike(null,e),true);close(k.hp,98.5);
});
test('preserved parry boons only fire on actual contact; Aftershock has separate .12s timer and no resource',()=>{
 const h=fresh(),g=h.game,q=g.cairnState(),k=pest(g),wide=pest(g,{x:g.P.x+50}),p=plot({id:3,x:g.P.x+10,health:.5,moisture:.2});g.gardenPlots=[p];Object.assign(g.rogueRun.perks,{counter:2,bedrock:2,aftershock:1,sanctuary:1});assert.equal(g.cairnBraceWorld(2),true);close(k.hp,100);close(wide.hp,100);close(p.health,.65);close(p.moisture,.32);assert.equal(g.cairnStrike(null,attack(g,k)),true);close(k.hp,96.95);close(wide.hp,99.2);h.advance(119);g.updateCairnCombat(.119);close(k.hp,96.95);h.advance(1);g.updateCairnCombat(.001);close(k.hp,95.95);close(wide.hp,99.2);assert.equal(q.strata,0);assert.equal(q.contactRemainder,0);assert.equal(q.aftershockPending,0);g.updateCairnCombat(.1);close(k.hp,95.95);
});
test('E reserves plates during .5 s and pays only one valid emergence; cancel keeps plates and cooldown',()=>{
 for(const hz of [30,60,120]){const h=fresh(),g=h.game,q=g.cairnState();q.strata=3;const place=g.cairnRidgePlacement();assert.equal(place.valid,true);const k=pest(g,{x:place.x,y:place.y-8});assert.equal(g.cairnBreakwaterWorld(4),true);assert.equal(q.strata,3);assert.equal(q.ridgeReserved,3);assert.equal(q.specialCool,0);assert.equal(g.cairnStoneWorld(k,5),false);tick(h,.5,hz);assert.equal(q.strata,0);assert.equal(q.ridgeReserved,0);assert.equal(q.ridgePhase,2);close(q.specialCool,20);close(k.hp,97.5);const count=g.stageLayout().platforms.length;tick(h,2,hz);assert.equal(q.ridgeBlockT,0);assert.ok(q.ridgeWardT>0);assert.equal(g.stageLayout().platforms.length,count);close(k.hp,97.5);tick(h,4,hz);assert.equal(q.ridgePhase,0);}
 for(const cause of ['dodge','move','air','water']){const h=fresh(),g=h.game,q=g.cairnState();q.strata=3;assert.equal(g.cairnBreakwaterWorld(1),true);if(cause==='dodge')g.P.dodgeT=.1;if(cause==='move')g.P.x+=7;if(cause==='air')g.P.grounded=false;if(cause==='water')g.P.wet=true;tick(h,.5,100);assert.equal(q.strata,3);assert.equal(q.ridgeReserved,0);assert.equal(q.specialCool,0);assert.equal(q.ridgePhase,0);}
});
test('Ridge bite ward is strongest radial protection only for bite, never invulnerability or other hazard guard',()=>{
 const h=fresh(),g=h.game,q=g.cairnState();q.strata=3;assert.equal(g.cairnBreakwaterWorld(1),true);tick(h,.5,100);const p=plot({id:10,x:q.ridgeX+40});g.gardenPlots=[p];close(g.cairnProtection(p,{kind:'bite',pointX:p.x,pointY:q.ridgeY}).fraction,.45);close(g.cairnProtection(p,{kind:'hazard',pointX:p.x,pointY:q.ridgeY}).fraction,0);g.P.grounded=false;close(g.cairnProtection(p,{kind:'bite',pointX:p.x,pointY:q.ridgeY}).fraction,.45);const e=attack(g,pest(g),'bite',p);assert.equal(g.cairnReducedBite(g.cairnProtection(p,{kind:'bite'}),e,{health:1,rawDamage:.1},{health:.955}),false);assert.equal(q.strata,0);
});
test('Ridge rejects real ladders and one-pixel gaps, allows touching support components and high unrelated ladders',()=>{
 const h=fresh(),g=h.game,base=g.P.y;g.P.y=base-40;g.P.platform='a';g.stageLayout().platforms.push({id:'a',x:180,y:base-40,w:54},{id:'b',x:234,y:base-40,w:60});assert.equal(g.cairnRidgePlacement().valid,true);g.stageLayout().platforms[1].x=235;assert.equal(g.cairnRidgePlacement().valid,false);g.stageLayout().platforms[1].x=234;g.stageLayout().ladders.push({x:248,w:14,top:base-70,bottom:base-20});assert.equal(g.cairnRidgePlacement().valid,false);g.stageLayout().ladders[0].top=base-170;g.stageLayout().ladders[0].bottom=base-120;assert.equal(g.cairnRidgePlacement().valid,true);
});
test('capture/restore bounds scalar state and resumes remaining private clocks without duplicate primary or parry',()=>{
 const h=fresh(),g=h.game,q=g.cairnState(),k=pest(g);assert.equal(g.cairnPrimaryWorld(k,3),true);h.advance(100);g.updateCairnCombat(.1);const captured=g.cairnCaptureState(q);close(captured.primaryWindup,.12);h.advance(5000);g.rogueRun.cairn=g.cairnRestoreState(captured,null);h.advance(120);g.updateCairnCombat(.12);close(k.hp,99);const copy=g.cairnCaptureState(g.cairnState());g.rogueRun.cairn=g.cairnRestoreState(copy,null);g.updateCairnCombat(.1);close(k.hp,99);const bad=g.cairnRestoreState({...copy,strata:99,stoneTravel:999,braceAge:99,ridgeReserved:99,stoneVX:999,primaryStartTag:Infinity});assert.equal(bad.strata,3);assert.equal(bad.stoneTravel,72);assert.equal(bad.braceAge,3);assert.equal(bad.ridgeReserved,0);assert.equal(bad.stoneVX,80);
});
test('High Tide uses actual waterline/head for all actions and current bent stem for guard/placement',()=>{
 const h=fresh('high-tide'),g=h.game,q=g.cairnState(),s=g.rogueRun.survival;s.waterY=g.P.y-60;q.strata=3;assert.equal(g.waterAt(g.P.x),null);assert.equal(g.cairnWetBody(g.P),true);assert.equal(g.cairnPrimaryWorld(pest(g),1),false);assert.equal(g.cairnStoneWorld({x:g.P.x+60,y:g.P.y},2),false);assert.equal(g.cairnBraceWorld(3),false);assert.equal(g.cairnBreakwaterWorld(4),false);assert.equal(q.strata,3);
});
test('actual water-point height permits a dry ledge above a pond and denies submerged Tide footing while the head breathes',()=>{
 const h=fresh(),g=h.game;let pond;for(let x=1500;x<20000&&!pond;x+=10)pond=g.waterAt(x);assert.ok(pond);g.P.x=pond.cx-48;g.P.y=pond.level-30;g.P.platform='pond-ledge';g.stageLayout().platforms=[{id:'pond-ledge',x:pond.cx-100,y:g.P.y,w:200}];assert.ok(g.waterAt(g.P.x));assert.equal(g.cairnWetPoint(g.P.x,g.P.y),false);assert.equal(g.cairnRidgePlacement().valid,true);assert.equal(g.cairnBraceWorld(1),true);g.P.y=pond.level+8;g.stageLayout().platforms[0].y=g.P.y;assert.equal(g.cairnWetPoint(g.P.x,g.P.y),true);g.updateCairnCombat(.01);assert.equal(g.cairnState().braceT,0);
 const tide=fresh('high-tide'),t=tide.game,s=t.rogueRun.survival,tip=t.highTideTip();t.P.x=tip.x+10;t.P.y=tip.y;t.P.platform='tide-foot';t.stageLayout().platforms=[{id:'tide-foot',x:t.P.x-100,y:t.P.y,w:200}];s.waterY=t.P.y-8;assert.equal(t.cairnWetBody(t.P),false);assert.equal(t.cairnWetPoint(t.P.x,t.P.y),true);assert.equal(t.cairnBraceWorld(2),false);const p=plot({id:81,x:s.root,tideVine:true});t.gardenPlots=[p];assert.equal(t.cairnProtection(p,{kind:'bite',pointX:tip.x,pointY:tip.y}).fraction,0);
});
