const {test}=require('node:test');
const assert=require('node:assert/strict');
const {loadGame}=require('./game-harness.cjs');
const ids=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222'];
function setup(classId='mech',difficulty='medium'){const h=loadGame();h.game.resetRogueRun('TEST',{classId,difficulty,mode:'high-tide'});return h;}
function start(g){g.plantGardenSeed(0);assert.equal(g.gardenPlots.length,1);return g.highTidePlant();}
function step(g,seconds,held=false){g.heldSpace=held;for(let t=0;t<seconds-1e-8;t+=.05)g.updateHighTide(Math.min(.05,seconds-t));}
function race(g,hz=60){const p=start(g);assert.equal(g.beginClimb(p,false),true);let pumping=true;for(let i=0;i<hz*120&&!g.rogueRun.ended;i++){const s=g.rogueRun.survival,gap=s.height-(s.base-g.P.y);if(gap>40||s.height>=480)pumping=false;else if(gap<2)pumping=true;g.heldSpace=pumping;g.updatePlayer(1/hz,{axis:0,top:g.WALK_V});g.updateGardenFun(1/hz);g.updateRunCompetition(1/hz);}return g.rogueRun.survival;}
function pair(){const room={host:ids[0],mode:'high-tide',members:ids.map((id,i)=>({id,slot:i+1,classId:i?'polge':'mech'}))};const players=ids.map((id,i)=>{const h=loadGame();h.game.beginCoop({room,user:{id},host:i===0,action(){return true;},tick(){}});return h;});return {room,players,sync(){players[1].game.coopState(JSON.parse(JSON.stringify(players[0].game.coopCapture())));}};}
test('High Tide is available without a login, account grant or impersonation',async()=>{const {relicCollection}=await import('../relics.mjs');for(const u of [null,{}, {id:'guest',is_anonymous:true},{id:'player',email:'person@players.max.invalid'}])assert.deepEqual(relicCollection(u).map(r=>r.id),['high-tide']);assert.ok(relicCollection({id:'owner',email:'lukketsvane@players.max.invalid'}).some(r=>r.id==='last-seed'));});
test('planting starts one finite shared vine; waiting, harvesting, seed pickups and spam do not win',()=>{const g=setup().game;const before=JSON.stringify(g.rogueRun.survival);step(g,8);g.updateRunCompetition(8);assert.equal(JSON.stringify(g.rogueRun.survival),before);assert.equal(g.runElapsed,0);const p=start(g);assert.equal(p.tideHeight,24);g.spawnLooseSeeds(0,g.P.y,9);g.collectSeed({amount:9});g.harvestGardenPlot(p);g.plantGardenSeed(80);g.winRogueRun();assert.equal(g.gardenSeeds,0);assert.equal(g.seedPickups.length,0);assert.equal(g.gardenPlots.length,1);assert.equal(g.rogueRun.ended,false);step(g,4,true);assert.ok(p.tideHeight<=53,'holding at the root cannot grow the whole route');assert.equal(g.floatKrek.length,0);g.enterLevel(2);assert.equal(g.rogueRun.world,1);});
test('every character can grow and physically reach the crown; normal scores remain untouched',()=>{for(const classId of ['mech','runner','bulwark','herbalist','polge','sligo']){const g=setup(classId).game,s=race(g);assert.equal(g.runWon,true,classId);assert.equal(g.rogueRun.ended,true);assert.equal(s.height,480);assert.ok(s.best>=478);assert.ok(s.elapsed>40&&s.elapsed<70,JSON.stringify(s));assert.equal(g.rogueMeta.runs||0,0);assert.equal(g.rogueRun.garden.length,1);assert.equal(g.rogueRun.garden[0].tideHeight,480);}});
test('the same grow/climb rhythm works at 30, 60 and 120 Hz, including Insane',()=>{let elapsed=[];for(const hz of [30,60,120]){const g=setup('bulwark','insane').game,s=race(g,hz);assert.equal(g.runWon,true,'rate '+hz);elapsed.push(s.elapsed);}assert.ok(Math.max(...elapsed)-Math.min(...elapsed)<1);});
test('the sea warns then surges and never rubber-bands to the player',()=>{const g=setup().game;start(g);const s=g.rogueRun.survival;s.elapsed=29.1;s.waterY=s.base+1000;g.updateHighTide(.1);assert.equal(s.phase,'warning');const y=s.waterY;g.updateHighTide(.1);const ordinary=y-s.waterY;s.elapsed=32.1;const y2=s.waterY;g.updateHighTide(.1);assert.equal(s.phase,'surge');assert.ok(y2-s.waterY>ordinary*1.5);const frozen=JSON.stringify(s);g.menuPaused=true;g.updateHighTide(1);assert.equal(JSON.stringify(s),frozen);g.menuPaused=false;g.P.y-=100;const y3=s.waterY;g.updateHighTide(.1);assert.ok(y3-s.waterY<2);});
test('a short dunk is recoverable, but shields, dodges and tun cannot prevent drowning',()=>{const g=setup('sligo').game;start(g);const s=g.rogueRun.survival,v=g.seedVital();s.waterY=g.P.y-60;g.P.dodgeT=10;g.P.tun=10;v.shield=10;step(g,.6);assert.ok(v.air<2.1&&v.hp===100);s.waterY=g.P.y+20;step(g,1);assert.equal(v.air,g.highTideProfile().breath);s.waterY=g.P.y-60;step(g,3);assert.equal(v.hp,0);assert.equal(g.rogueRun.ended,true);assert.equal(g.runWon,false);g.resetRogueRun('RETRY',{mode:'high-tide'});assert.equal(g.gardenSeeds,1);assert.equal(g.rogueRun.survival.started,false);assert.equal(g.seedDown(),false);});
test('dew is claimed once, grows only the actual plant and slows but never reverses the sea',()=>{const g=setup().game,p=start(g),s=g.rogueRun.survival;s.height=p.tideHeight=150;s.elapsed=20;s.waterY=s.base-50;g.P.x=48;g.P.y=s.base-128;g.P.grounded=true;const before=s.waterY;g.updateHighTide(.05);assert.equal(s.dewMask,1);assert.equal(s.height,174);assert.ok(s.waterY<before);const after=s.height;step(g,.5);assert.equal(s.height,after);assert.ok(s.calm>0);assert.equal(g.gardenPlots.length,1);});
test('guest tend is validated at the tip and cannot set water, growth or health; handoff preserves the race',()=>{const {players:[h,j],room,sync}=pair(),g=h.game,q=j.game;start(g);sync();const s=g.rogueRun.survival,m=g.coop.members[ids[1]];q.P.x=1;q.P.y=s.base-12;q.P.st='climb';q.P.grounded=false;q.heldSpace=true;g.coopInput(ids[1],{avatar:{...q.coopAvatar(),waterY:-10000,hp:999,tideHeight:480},actions:[]});step(g,.2);assert.ok(s.height>24&&s.height<30);sync();assert.equal(q.rogueRun.survival.height,s.height);const frozen=JSON.stringify(q.rogueRun.survival);q.updateHighTide(1);assert.equal(JSON.stringify(q.rogueRun.survival),frozen);h.advance(1000);const height=s.height;step(g,.2);assert.equal(s.height,height,'stale input never pumps indefinitely');sync();q.coopRoster({...room,host:ids[1],members:[room.members[1]]});q.heldSpace=false;q.updateHighTide(.1);assert.equal(q.rogueRun.survival.height,height);assert.ok(q.rogueRun.survival.elapsed>s.elapsed);assert.equal(q.gardenSeeds,0);});
test('a new teammate joins on a real grown dry branch, and an ended race replicates to guests',()=>{const {players:[h,j],sync}=pair(),g=h.game,q=j.game,p=start(g),s=g.rogueRun.survival;s.height=p.tideHeight=220;s.waterY=s.base-90;g.P.x=0;g.P.y=s.base-200;delete g.coop.members[ids[1]];assert.equal(g.coopJoin(ids[1],{classId:'polge'}),true);const m=g.coop.members[ids[1]];assert.equal(m.avatar.y,s.base-192);assert.ok(g.stageLayout().platforms.some(p=>p.y===m.avatar.y));sync();assert.equal(q.P.y,m.avatar.y);for(const a of g.coopCapture().members)g.seedVital(g.coop.members[a.id]).hp=0;g.updateHighTide(.1);sync();assert.equal(q.rogueRun.ended,true);assert.equal(q.runWon,false);});
