const {test}=require('node:test');
const assert=require('node:assert/strict');
const {loadGame,plot}=require('./game-harness.cjs');
function fresh(mode){const h=loadGame(),g=h.game;g.resetRogueRun('MYCEL',{classId:'herbalist',skinId:'moon',difficulty:'medium',...(mode?{mode}:{})});g.floatKrek=[];g.gardenPlots=[];g.runHazards=[];g.runEncounters=[];g.wonders={};g.runExpedition=null;const L=g.stageLayout();L.platforms=[];L.ladders=[];L.spots={};Object.assign(g.P,{x:200,y:g.surfaceY(200),grounded:true,vx:0,vy:0,face:1,st:'free',wet:false,platform:null,dodgeT:0,tun:0,pounce:0});return h;}
function close(a,b){assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);}
function tick(h,seconds,hz=120,shots=false){for(let i=0;i<Math.round(seconds*hz);i++){h.advance(1000/hz);(shots?h.game.updateClassCombat:h.game.updateMycelCombat)(1/hz);}}
function pest(g,dx=20,fields={}){const k=Object.assign(g.makeKrek(1,false,0),{x:g.P.x+dx,y:g.P.y-13,hp:100,maxHp:100,raid:true,scout:false,queen:false,boss:false,elite:false,windup:0,face:-1},fields);g.floatKrek.push(k);return k;}
function stock(g,culture){g.rogueRun.mycel=g.mycelRestoreState({world:g.rogueRun.world,culture});return g.mycelState();}

test('actual initial darts earn once, preserve1D/.65D and have no shared reward gate',()=>{
 for(const hz of [30,60,120]){const h=fresh(),g=h.game,a=pest(g,24),b=pest(g,50);g.gardenPlots=[plot({id:1,x:g.P.x+24,health:.9,moisture:.1})];assert.equal(g.mycelPrimaryWorld(a,1),true);tick(h,.3,hz,true);close(a.hp,99);close(b.hp,99.35);close(g.mycelState().culture,.5);h.advance(300);g.updateMycelCombat(.01);assert.equal(g.mycelPrimaryWorld(a,2),true);tick(h,.3,hz,true);close(g.mycelState().culture,1);assert.equal(g.classShots.length,0);}
});
test('miss, wall and objective-only dart contacts grant no Culture; chains require distinct LOS targets',()=>{
 const h=fresh(),g=h.game,a=pest(g,24),b=pest(g,46);g.rogueRun.perks.outbreak=1;g.stageLayout().platforms.push({id:'wall',x:g.P.x+35,y:g.P.y-40,w:3,h:45,solid:true});assert.equal(g.mycelPrimaryWorld(a,1),true);tick(h,.3,120,true);close(a.hp,99);close(b.hp,100);close(g.mycelState().culture,.5);
 const miss=fresh(),m=miss.game;pest(m,50);m.stageLayout().platforms.push({id:'stop',x:m.P.x+14,y:m.P.y-40,w:3,h:45,solid:true});assert.equal(m.mycelPrimaryWorld({x:m.P.x+60,y:m.P.y-13},1),true);tick(miss,.4,120,true);close(m.mycelState().culture,0);assert.equal(m.classShots.length,0);
});
test('owned Ferment/Colony/Outbreak remain bounded and accepted build cannot borrow later upgrades',()=>{
 const h=fresh(),g=h.game,a=pest(g,24),b=pest(g,70),c=pest(g,105),d=pest(g,140),far=pest(g,180);g.gardenPlots=[plot({id:1,x:g.P.x+24,moisture:.1})];Object.assign(g.rogueRun.perks,{ferment:2,colony:2,outbreak:1});assert.equal(g.mycelPrimaryWorld(a,1),true);Object.assign(g.rogueRun.perks,{ferment:3,colony:3});tick(h,.3,120,true);close(a.hp,98.6);for(const k of [b,c,d])close(k.hp,99.09);close(far.hp,100);close(g.mycelState().culture,.5);
});
test('wet-plot passive uses actual simulation at most1/s, dry links remain and cap6 never decays',()=>{
 for(const hz of [30,60,120]){const h=fresh(),g=h.game;g.gardenPlots=[plot({id:1,x:g.P.x+3,moisture:.1}),plot({id:2,x:g.P.x+12,moisture:.2}),plot({id:3,x:g.P.x+20,moisture:.2}),plot({id:4,x:g.P.x+30,moisture:.2})];tick(h,1,hz);close(g.mycelState().culture,1);assert.equal(g.mycelNetwork().length,3);tick(h,5,hz);close(g.mycelState().culture,6);g.gardenPlots.forEach(p=>p.moisture=0);tick(h,1,hz);close(g.mycelState().culture,6);}
 const h=fresh(),g=h.game,p=plot({id:1,x:g.P.x+20,moisture:.2});g.gardenPlots=[p];tick(h,1);close(g.mycelState().culture,.5);g.stageLayout().platforms.push({id:'wall',x:g.P.x+9,y:g.P.y-40,w:8,h:45,solid:true});tick(h,1);close(g.mycelState().culture,.5);assert.equal(g.mycelNetwork().length,0);
});
test('Cloud pays once, pulses exactly at1/2/3 and Ferment extends slow only without generic stagger',()=>{
 for(const rank of [0,3]){const h=fresh(),g=h.game,q=stock(g,6),a=pest(g,28,{windup:.7,chargeT:.4});g.rogueRun.perks.ferment=rank;assert.equal(g.mycelCloudWorld({x:a.x,y:a.y},1),true);close(q.culture,4);close(q.cloudCool,5);h.advance(999);g.updateMycelCombat(.01);close(a.hp,100);h.advance(1);g.updateMycelCombat(.001);close(a.hp,99.75);assert.equal(a.windup,.7);assert.equal(a.chargeT,.4);close(g.mycelSlowFactor(a),.7);tick(h,2);close(a.hp,99.25);assert.equal(q.clouds.length,rank?1:0);tick(h,2);close(a.hp,99.25);if(rank){assert.equal(q.clouds[0].pulseMask,7);close(g.mycelSlowFactor(a),.7);}const boss=pest(g,29,{boss:true,finalBoss:false});close(g.mycelSlowFactor(boss),rank?.9:1);}
});
test('Cloud point/population denial is unpaid and live overlap does not stack slow',()=>{
 const h=fresh(),g=h.game,q=stock(g,6);g.rogueRun.perks.ferment=3;const at={x:g.P.x+25,y:g.P.y-13};assert.equal(g.mycelCloudWorld({x:g.P.x+81,y:g.P.y-12},1),false);close(q.culture,6);close(q.cloudCool,0);assert.equal(g.mycelCloudWorld(at,2),true);tick(h,5.01);assert.equal(g.mycelCloudWorld(at,3),true);assert.equal(q.clouds.length,2);const a=pest(g,25);close(g.mycelSlowFactor(a),.7);q.cloudCool=0;g.rogueRun.mycel=g.mycelRestoreState(g.mycelCaptureState(q));g.rogueRun.mycel.cloudCool=0;const copied=g.mycelCaptureState(g.rogueRun.mycel);copied.cloudCool=0;g.rogueRun.mycel=g.mycelRestoreState(copied);assert.equal(g.mycelCloudWorld(at,4),false);close(g.mycelState().culture,2);close(g.mycelState().cloudCool,0);
});
test('Bloom fixed0/2/4 pulses deal base2.4 with absolute plot restoration and no channel lock',()=>{
 for(const hz of [30,60,120]){const h=fresh(),g=h.game,q=stock(g,4),k=pest(g,20),p=plot({id:10,x:g.P.x+12,health:.3,moisture:.1});g.gardenPlots=[p];assert.equal(g.mycelBloomWorld(1),true);close(k.hp,100);close(q.culture,0);close(q.specialCool,12);assert.equal(g.mycelPhasePolicy().blockTend,false);const centre=q.bloom.x;tick(h,.1,hz);close(k.hp,99.2);close(p.health,.34);close(p.moisture,.15);g.P.x+=150;tick(h,3.9,hz);assert.equal(q.bloom.x,centre);close(k.hp,97.6);close(p.health,.42);close(p.moisture,.25);assert.equal(q.bloom.pulseMask,7);close(q.bloom.plots[0].healthUsed,.12);close(q.bloom.plots[0].waterUsed,.15);}
});
test('empty or stone-separated Bloom denies without debit/readiness and real deferred cast remains bounded',()=>{
 const h=fresh(),g=h.game,q=stock(g,4);g.rogueRun.perks.symphony=1;g.bombCool=.4;assert.equal(g.mycelBloomWorld(1),false);close(q.culture,4);close(q.specialCool,0);close(g.bombCool,.4);const k=pest(g,30);g.stageLayout().platforms.push({id:'wall',x:g.P.x+12,y:g.P.y-35,w:3,h:45,solid:true});assert.equal(g.mycelBloomWorld(2),false);close(q.culture,4);g.stageLayout().platforms=[];assert.equal(g.mycelBloomWorld(3),true);g.P.wet=true;tick(h,.1);close(k.hp,100);assert.equal(q.bloom.cancelled,1);assert.equal(q.bloom.pulseMask,7);close(q.culture,0);assert.ok(q.specialCool>11);
});
test('Symbiosis debits each actual one-second per-plot budget and never credits chains',()=>{
 const h=fresh(),g=h.game,a=pest(g,20),b=pest(g,40),p=plot({id:3,x:g.P.x+20,health:.2,moisture:.1});g.gardenPlots=[p];Object.assign(g.rogueRun.perks,{symbiosis:3,cadence:3,outbreak:1});assert.equal(g.mycelPrimaryWorld(a,1),true);tick(h,.2,120,true);close(p.health,.245);close(p.moisture,.205);const first=g.mycelState().symbiosis[0];h.advance(400);g.updateMycelCombat(.01);assert.equal(g.mycelPrimaryWorld(a,2),true);tick(h,.2,120,true);close(p.health,.245);close(p.moisture,.205);close(first.healthUsed,.045);close(first.waterUsed,.105);const saved=g.mycelCaptureState(g.mycelState());g.rogueRun.mycel=g.mycelRestoreState(saved);h.advance(1100);g.updateMycelCombat(.01);assert.equal(g.mycelPrimaryWorld(a,3),true);tick(h,.2,120,true);close(p.health,.29);assert.ok(b.hp<100);assert.ok(g.mycelState().culture>=1.5);
});
test('zero-health retained Garden stub revives exact identity without old health/water minimum or archive fallback',()=>{
 const h=fresh(),g=h.game,q=stock(g,4),p=plot({id:11,x:g.P.x+12,health:0,moisture:.13,growth:.82,stalk:true,seed:123});g.gardenPlots=[p];assert.equal(g.plantFalls(p),true);const original={kind:p.kind,seed:p.seed,growth:p.growth,stalk:p.stalk};assert.equal(g.mycelBloomWorld(1),true);tick(h,.01,100);assert.equal(p.dead,0);close(p.health,.04);close(p.moisture,.18);assert.deepEqual({kind:p.kind,seed:p.seed,growth:p.growth,stalk:p.stalk},original);tick(h,3.99,100);close(p.health,.12);close(p.moisture,.28);assert.equal(q.bloom.reviveConsumed,1);
 const removed=fresh(),r=removed.game,stub=plot({id:12,x:r.P.x+12,health:0,dead:8,seed:124});r.gardenPlots=[stub];stock(r,4);assert.equal(r.mycelBloomWorld(2),true);r.gardenPlots=[];r.rogueRun.garden=[{id:stub.id,x:stub.x,kind:stub.kind,seed:stub.seed}];tick(removed,.1);assert.equal(r.gardenPlots.length,0);assert.equal(r.mycelState().bloom.reviveConsumed,1);
});
test('state/shot/mask capture is bounded and promotion preserves spent pulse and restoration debt',()=>{
 const h=fresh(),g=h.game,q=stock(g,4),k=pest(g,20),p=plot({id:1,x:g.P.x+12,health:.3,moisture:.1});g.gardenPlots=[p];assert.equal(g.mycelBloomWorld(1),true);tick(h,.1);const saved=g.mycelCaptureState(q);assert.equal(saved.bloom.pulseMask,1);g.rogueRun.mycel=g.mycelRestoreState(saved);g.updateMycelCombat(.01);close(k.hp,99.2);tick(h,3.9);close(k.hp,97.6);close(p.health,.42);const bad=g.mycelRestoreState({world:-1,culture:Infinity,clouds:[{serial:1,startTag:1,world:-3,age:0,life:3}],networkIds:[1,1,2,3,4]});assert.equal(bad.culture,0);assert.equal(bad.world,g.rogueRun.world);assert.equal(bad.clouds.length,0);assert.equal(bad.networkIds.length<=3,true);assert.doesNotThrow(()=>g.mycelCaptureShot({kind:'spore',primarySerial:1,startTag:1,seenIds:{evil:1}}));const invalid=g.mycelBurnContext({mycelBurnKind:'bloom',mycelBurnSerial:Infinity,mycelBurnWorld:1});assert.deepEqual(JSON.parse(JSON.stringify(invalid.restore(p,1,1))),{health:0,water:0});
});

test('expired former Symbiosis plots cannot exhaust the bounded ledger while active debt survives replacement',()=>{
 const h=fresh(),g=h.game,k=pest(g,20);g.rogueRun.perks.symbiosis=1;for(let id=1;id<=31;id++){const p=plot({id,x:g.P.x+20,health:.2,moisture:.1});g.gardenPlots=[p];assert.equal(g.mycelPrimaryWorld(k,id),true);tick(h,.2,120,true);close(p.health,.215);close(p.moisture,.135);h.advance(1001);g.updateMycelCombat(.001);}assert.ok(g.mycelState().symbiosis.length<=30);const current=g.gardenPlots[0];h.advance(600);g.updateMycelCombat(.001);assert.equal(g.mycelPrimaryWorld(k,32),true);tick(h,.2,120,true);close(current.health,.23);const saved=g.mycelCaptureState(g.mycelState());g.rogueRun.mycel=g.mycelRestoreState(saved);h.advance(400);g.updateMycelCombat(.001);assert.equal(g.mycelPrimaryWorld(k,33),true);tick(h,.2,120,true);close(current.health,.23);
});
