"""Compile the owner's Level Studio composition without substituting any art.

The authoring coordinates are the native game coordinates. Collision-only
objects never paint. The bitmap and collision table share the same origin.
"""
from pathlib import Path
import hashlib
import json
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'docs/asset-review/high-tide-v1'
level = json.loads((SOURCE / 'level.json').read_text())
assets = {a['id']: Image.open(SOURCE / a['src']).convert('RGBA') for a in level['assets']}
x0, y0, width, height = 0, -44, 628, 1614
scene = Image.new('RGBA', (width, height), '#080a0f')
for obj in level['objects']:
    if not obj.get('asset') or obj.get('opacity', 1) <= 0:
        continue
    assert not obj.get('rotation'), 'Bake rotated objects explicitly before changing this export'
    atlas = assets[obj['asset']]
    crop = obj.get('crop') or dict(x=0, y=0, w=1, h=1)
    left, top = round(crop['x']*atlas.width), round(crop['y']*atlas.height)
    sprite = atlas.crop((left, top, left+round(crop['w']*atlas.width), top+round(crop['h']*atlas.height)))
    sprite = sprite.resize((round(obj['w']), round(obj['h'])), Image.Resampling.NEAREST)
    if obj.get('flip'):
        sprite = sprite.transpose(Image.Transpose.FLIP_LEFT_RIGHT)
    opacity = obj.get('opacity', 1)
    sprite.putalpha(sprite.getchannel('A').point(lambda a: round(a*opacity)))
    scene.alpha_composite(sprite, (round(obj['x'])-x0, round(obj['y'])-y0))
target = ROOT / 'assets/levels-v1/high-tide.png'
scene.save(target, optimize=True)

# Authoring names retain the route category and garden number, but never ship as UI.
platforms = []
for obj in level['objects']:
    if obj['kind'] != 'platform':
        continue
    route = 0 if 'Hovudrute' in obj['name'] else 1 if 'Sideveg' in obj['name'] else 2
    platforms.append([obj['x'], obj['y'], obj['w'], route, int(obj['name'][:2])])
data = dict(name=level['name'], origin=level['spawn'], x=x0, y=y0, w=width, h=height,
            art='assets/levels-v1/high-tide.png', objects=len(level['objects']), platforms=platforms)
(ROOT / 'high-tide-map.js').write_text('/* Generated by scripts/build-high-tide.py. */\nwindow.MaxHighTideMap='+json.dumps(data,ensure_ascii=False,separators=(',', ':'))+';\n')
pending_path = ROOT / 'assets/figma-pending.json'
pending = json.loads(pending_path.read_text())
entry = dict(path=str(target.relative_to(ROOT)), sha1=hashlib.sha1(target.read_bytes()).hexdigest(),
             width=width, height=height, note="Owner's complete five-garden composition; scripts/build-high-tide.py. Figma desktop MCP unavailable.")
pending['files'] = [e for e in pending['files'] if e['path'] != entry['path']] + [entry]
pending_path.write_text(json.dumps(pending, indent=1)+'\n')
print(f'{width}x{height}: {len(platforms)} invisible floors; all 178 art objects preserved')
